name: Comment Triggers

on:
  issue_comment:
    types: [created]

jobs:
  run-on-comment:
    if: github.event.comment.body == '@code-review-bott resolve'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies/requirements.txt

      - name: Run a script
        env:
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GITHUB_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Triggered by @code-review-bott resolve comment"
          python bot_comments_resolver.py



