name: Comment Triggers

on:
  issue_comment:
    types: [created]

jobs:
  debug-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Comment Context
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Is PR Comment: ${{ github.event.issue.pull_request != null }}"
          echo "PR Number: ${{ github.event.issue.pull_request.number }}"

  run-on-comment:
    if: |
      contains(github.event.comment.body, '@code-review-bott resolve') && 
      (github.event.issue.pull_request || github.event.pull_request)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies/requirements.txt

      - name: Run a script
        env:
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GITHUB_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Triggered by @code-review-bott resolve comment"
          python bot_comments_resolver.py



